### PR TITLE
fixes to code

### PR DESCRIPTION
**Pull request by elosoman**
So in using your project I ran into a couple of errors.

1. URL was not defined in feed.js.
2. Apparently when there are no events, ics is undefined so empty string was assumed in generate-ics.js.

Other than this it appears to be working. If I had more time I would contribute a test or two :)

Thanks for your effort.
Ben

### CODE REVIEW

**Comment by derhuerst** [comment]
> 1. URL was not defined in feed.js.

Which version of Node.js are you running it with? [Node.js v10 added the `URL` global](https://nodejs.org/docs/latest-v10.x/api/globals.html#globals_url) and [v10 is the minimum required version for `ics-service`](https://github.com/derhuerst/ics-service/blob/30e77888d29f6d875c312301dccea2d62ff6aa65/package.json#L25).

> 2. Apparently when there are no events, ics is undefined so empty string was assumed in generate-ics.js.

Thanks for reporting this!

Your commits introduce a new bug though (`ics || ''.indexOf`), so I'm going to fix this in a different commit.

**Comment by derhuerst** [comment]
> 2. Apparently when there are no events, `ics` is undefined so empty string was assumed in `generate-ics.js`.

Published a fix to npm as `ics-service@1.2.1`.

**Comment by elosoman** [comment]
Unfortunately an older version of MeteorJS = node v8
thanks

**Comment by derhuerst** [comment]
> Unfortunately an older version of MeteorJS = node v8

I can understand your situation, but [Node.js v8 has been out of long-term support for a while, even v10 is out of long-term support by now](https://nodejs.org/en/about/releases/).

You should see a warning that your Node.js version does not support this package.

**Pull request closed without merging**
